# Copyright 2025 Canonical
# See LICENSE file for licensing details.

"""Management of the packages.ubuntu.com workload.

This module owns everything that happens on the machine: installing the
dependencies, checking out the application source, generating its configuration
with the upstream ``bin/setup-site`` helper, serving it through Apache and
refreshing the package indexes on a schedule via a systemd timer.
"""

import logging
import os
import shutil
import subprocess
from pathlib import Path

from charmlibs import apt, systemd
from charmlibs.apt import PackageError, PackageNotFoundError

logger = logging.getLogger(__name__)


class SetupSiteError(Exception):
    """Raised when the upstream setup-site helper fails to generate config."""


TOPDIR = Path("/srv/packages.ubuntu.com")
SITE = "packages.ubuntu.com"
RUN_USER = "ubuntu"
RUN_GROUP = "ubuntu"
APACHE_USER = "www-data"

REPO_URL = "https://salsa.debian.org/webmaster-team/packages.git"
REPO_BRANCH = "ubuntu-master"

SERVICE = "packages-daily"
DEFAULT_SYNC_HOURS = "3,9,15,21"

KEYRING_PATH = "/usr/share/keyrings/debian-archive-keyring.gpg"
APACHE_SITE_PATH = Path(f"/etc/apache2/sites-available/{SITE}.conf")
CONFIG_OVERRIDES_MARKER = "# --- charm-managed overrides (ubuntu-packages) ---"

# System and Perl packages required to build the indexes and serve the site.
PACKAGES = [
    "apache2",
    "libapache2-mod-perl2",
    "git",
    "procmail",
    "wget",
    "gettext",
    "debian-archive-keyring",
    "apt-xapian-index",
    "python3-xapian",
    "libsearch-xapian-perl",
    "liblingua-stem-perl",
    "liblingua-pt-stemmer-perl",
    "liblingua-stem-snowball-da-perl",
    "libtemplate-perl",
    "liblocale-maketext-lexicon-perl",
    "libnumber-format-perl",
    "libcgi-pm-perl",
    "libcgi-session-perl",
    "libi18n-acceptlanguage-perl",
    "libhtml-template-perl",
    "libhtml-parser-perl",
    "libio-stringy-perl",
    "libmldbm-perl",
    "libtext-iconv-perl",
    "libclass-accessor-perl",
    "liburi-perl",
    "libxml-rss-perl",
]

# Apache modules the application relies on.
APACHE_MODULES = [
    "perl",
    "expires",
    "headers",
    "rewrite",
    "negotiation",
    "status",
    "cgid",
]

# Runtime directories that must exist (and stay writable) before Apache starts,
# even on a fresh install where no archive sync has run yet.
RUNTIME_DIRS = [
    TOPDIR / "www",
    TOPDIR / "files",
    TOPDIR / "files" / "logs",
]

# Apache validates RewriteMap txt: source files at startup. This one is normally
# generated by the daily sync (cron.d/400changelogs_map), so it must exist as an
# empty placeholder on a fresh install for Apache to start.
CHANGELOGS_MAP = TOPDIR / "files" / "changelogs-map"


class PackagesManager:
    """Drive the packages.ubuntu.com workload on the unit."""

    def __init__(self):
        logger.debug("PackagesManager init")
        self.env = os.environ.copy()
        self.proxies = {}
        juju_http_proxy = self.env.get("JUJU_CHARM_HTTP_PROXY")
        juju_https_proxy = self.env.get("JUJU_CHARM_HTTPS_PROXY")
        if juju_http_proxy:
            logger.debug("Setting HTTP_PROXY env to %s", juju_http_proxy)
            self.env["HTTP_PROXY"] = juju_http_proxy
            self.env["http_proxy"] = juju_http_proxy
            self.proxies["http"] = juju_http_proxy
        if juju_https_proxy:
            logger.debug("Setting HTTPS_PROXY env to %s", juju_https_proxy)
            self.env["HTTPS_PROXY"] = juju_https_proxy
            self.env["https_proxy"] = juju_https_proxy
            self.proxies["https"] = juju_https_proxy

    def _run(self, args: list[str], cwd: Path | None = None):
        """Run a command, raising CalledProcessError on failure."""
        logger.debug("Running command: %s", " ".join(args))
        subprocess.run(args, cwd=cwd, env=self.env, check=True)

    def _install_packages(self):
        """Install the required apt packages."""
        apt.update()
        logger.debug("Apt index refreshed.")
        for package in PACKAGES:
            try:
                apt.add_package(package)
                logger.debug("Package %s installed", package)
            except PackageNotFoundError:
                logger.error("Failed to find package %s in package cache", package)
                raise
            except PackageError as e:
                logger.error("Failed to install %s: %s", package, e)
                raise

    def _clone_or_update_source(self):
        """Clone the application source, or fast-forward an existing checkout."""
        if (TOPDIR / ".git").is_dir():
            logger.debug("Updating existing checkout in %s", TOPDIR)
            self._run(["git", "fetch", "origin", REPO_BRANCH], cwd=TOPDIR)
            self._run(["git", "reset", "--hard", f"origin/{REPO_BRANCH}"], cwd=TOPDIR)
        else:
            logger.debug("Cloning %s into %s", REPO_URL, TOPDIR)
            TOPDIR.parent.mkdir(parents=True, exist_ok=True)
            self._run(
                ["git", "clone", "--branch", REPO_BRANCH, REPO_URL, str(TOPDIR)],
            )

    def _run_setup_site(self):
        """Generate the application configuration via the upstream helper.

        The upstream ``bin/setup-site`` script ends each loop iteration with a
        short-circuited ``[ -n "$verbose" ] && ...`` test. When not run with
        ``-v`` that test evaluates false, so the script returns a non-zero exit
        code even on success. We therefore ignore its exit code and instead
        verify that the expected files were generated with the substitutions
        applied.
        """
        logger.debug("Running command: ./bin/setup-site %s %s", TOPDIR, SITE)
        subprocess.run(
            ["./bin/setup-site", str(TOPDIR), SITE],
            cwd=TOPDIR,
            env=self.env,
            check=False,
        )
        config_sh = TOPDIR / "config.sh"
        expected = [config_sh, TOPDIR / "conf" / "apache.conf", TOPDIR / "bin" / "daily"]
        missing = [str(path) for path in expected if not path.is_file()]
        if missing:
            raise SetupSiteError(
                "setup-site did not generate expected files: " + ", ".join(missing)
            )
        if "%TOPDIR%" in config_sh.read_text(encoding="utf-8"):
            raise SetupSiteError("setup-site did not substitute placeholders in config.sh")

    def _ensure_runtime_dirs(self):
        """Create the runtime directories and the Apache-writable cache."""
        for directory in RUNTIME_DIRS:
            directory.mkdir(parents=True, exist_ok=True)

        # Placeholder for the RewriteMap source until the first sync generates it.
        if not CHANGELOGS_MAP.exists():
            CHANGELOGS_MAP.touch()

        cache_dir = TOPDIR / "cache"
        cache_dir.mkdir(parents=True, exist_ok=True)
        # The cache must be writable by the Apache worker processes.
        shutil.chown(cache_dir, APACHE_USER, APACHE_USER)
        cache_dir.chmod(0o2770)

    def _link_keyring(self):
        """Point the application at the system Debian archive keyring."""
        trusted = TOPDIR / "conf" / "trusted.gpg"
        if trusted.is_symlink() or trusted.exists():
            trusted.unlink()
        trusted.symlink_to(KEYRING_PATH)

    def _setup_apache(self):
        """Enable required modules and install the application virtual host."""
        for module in APACHE_MODULES:
            self._run(["a2enmod", "--quiet", module])

        shutil.copy("src/apache/packages.conf", APACHE_SITE_PATH)
        self._run(["a2ensite", "--quiet", f"{SITE}.conf"])
        self._run(["a2dissite", "--quiet", "000-default"])

    def _fix_ownership(self):
        """Give the checkout to the run user, keeping the cache for Apache."""
        self._run(["chown", "-R", f"{RUN_USER}:{RUN_GROUP}", str(TOPDIR)])
        cache_dir = TOPDIR / "cache"
        if cache_dir.is_dir():
            shutil.chown(cache_dir, APACHE_USER, APACHE_USER)
            cache_dir.chmod(0o2770)

    def install(self):
        """Install dependencies, check out the source and configure Apache."""
        self._install_packages()
        self._clone_or_update_source()
        self._run_setup_site()
        self._ensure_runtime_dirs()
        self._link_keyring()
        self._setup_apache()
        self._fix_ownership()

    def _render_config_overrides(self, options: dict[str, str]) -> str:
        """Build the shell override block appended to the generated config.sh."""
        suites = " ".join(options["suites"].split())
        architectures = " ".join(options["architectures"].split())
        lines = [
            "",
            CONFIG_OVERRIDES_MARKER,
            f'ftpsite="{options["ftpsite"]}"',
            f'security_ftpsite="{options["security_ftpsite"]}"',
            f'debports_ftpsite="{options["debports_ftpsite"]}"',
            f'architectures="{architectures}"',
            f'suites="{suites}"',
            'dists="$suites"',
            "for _suite in $suites; do",
            '    _arch_var="arch_$(echo $_suite | sed \'s/-/_/g\')"',
            '    eval "${_arch_var}=\\"$architectures\\""',
            "done",
            "",
        ]
        return "\n".join(lines)

    def configure(self, options: dict[str, str]):
        """Apply charm configuration to the generated application config."""
        config_path = TOPDIR / "config.sh"
        content = config_path.read_text(encoding="utf-8")

        marker_index = content.find(CONFIG_OVERRIDES_MARKER)
        if marker_index != -1:
            # Drop any previously appended override block before re-adding it.
            content = content[:marker_index].rstrip("\n") + "\n"

        content += self._render_config_overrides(options)
        config_path.write_text(content, encoding="utf-8")
        shutil.chown(config_path, RUN_USER, RUN_GROUP)

    def _parse_sync_hours(self, sync_hours: str) -> list[int]:
        """Parse comma-separated hour values in the range [0, 23]."""
        raw_values = [value.strip() for value in sync_hours.split(",") if value.strip()]
        if not raw_values:
            raise ValueError("sync hours cannot be empty")

        parsed_hours = []
        for value in raw_values:
            hour = int(value)
            if hour < 0 or hour > 23:
                raise ValueError("sync hours must be between 0 and 23")
            if hour not in parsed_hours:
                parsed_hours.append(hour)
        return parsed_hours

    def configure_schedule(self, sync_hours: str):
        """Write the timer unit from configured hours and restart the timer."""
        hours = self._parse_sync_hours(sync_hours)

        timer_lines = [
            "[Unit]",
            "Description=packages.ubuntu.com - Scheduled archive synchronization",
            "",
            "[Timer]",
        ]
        timer_lines.extend(f"OnCalendar=*-*-* {hour:02d}:23:00" for hour in hours)
        timer_lines.extend(
            [
                "Persistent=true",
                "RandomizedDelaySec=300",
                "",
                "[Install]",
                "WantedBy=timers.target",
                "",
            ]
        )

        timer_path = Path(f"/etc/systemd/system/{SERVICE}.timer")
        timer_path.write_text("\n".join(timer_lines), encoding="utf-8")
        systemd.daemon_reload()
        systemd.service_restart(f"{SERVICE}.timer")

    def setup_systemd_units(self):
        """Install the daily service and timer with proxy configuration."""
        systemd_unit_location = Path("/etc/systemd/system")
        systemd_unit_location.mkdir(parents=True, exist_ok=True)

        service_content = Path(f"src/systemd/{SERVICE}.service").read_text(encoding="utf-8")

        proxy_env_vars = ""
        if "http" in self.proxies:
            proxy_env_vars += "\nEnvironment=http_proxy=" + self.proxies["http"]
            proxy_env_vars += "\nEnvironment=HTTP_PROXY=" + self.proxies["http"]
        if "https" in self.proxies:
            proxy_env_vars += "\nEnvironment=https_proxy=" + self.proxies["https"]
            proxy_env_vars += "\nEnvironment=HTTPS_PROXY=" + self.proxies["https"]
        service_content += proxy_env_vars

        (systemd_unit_location / f"{SERVICE}.service").write_text(
            service_content, encoding="utf-8"
        )

        self.configure_schedule(DEFAULT_SYNC_HOURS)
        systemd.service_enable(f"{SERVICE}.timer")

    def start(self):
        """Start the Apache web server."""
        systemd.service_restart("apache2")

    def trigger_sync(self):
        """Trigger an archive synchronization run without blocking."""
        systemd.service_start(f"{SERVICE}.service", "--no-block")

    def run_sync(self):
        """Trigger a blocking archive synchronization run."""
        systemd.service_start(f"{SERVICE}.service")
